### ISSUE TITLE
statistiche

### ISSUE THREAD

**Issue by grammaton** [s-e-a-m/SPhoMaMo#3]
- invertire righe e colonne per grafica verticale
 - sistemare indicatori sugli assi

**Comment by Petapton** [comment]
Invertendo le righe e le colonne non si riesce a confrontare la risposta dello stesso microfono al variare dell'angolo, ma si confronta la risposta allo stesso angolo dei diversi microfoni.
Non è più immediata la variazione delle ampiezze tra i canali dx e sx e viene meno l'utilità del grafico (?).
Secondo me ha poco senso :face_with_head_bandage:

**Comment by grammaton** [comment]
Nel senso che la lettura verticale è meno confrontabile?

**Comment by Petapton** [comment]
Yeppers
![Schermata da 2022-03-22 16-26-38](https://user-images.githubusercontent.com/14984292/159518127-27ebd3b3-97e2-48e9-8abd-314afc9ba61a.png)

**Comment by grammaton** [comment]
però diventano molto più leggibili le differenti risposte a parità di angolo… :)

**Comment by Petapton** [comment]
Questo di sicuro. È la soluzione che ci meritiamo ma di cui non abbiamo bisogno. Che faccio lascio?

**Comment by Petapton** [comment]
[Split dei graficoni su due pagine](https://github.com/s-e-a-m/SPhoMaMo/commit/c02a73b49941967405669f6d6e48ff1015fa504c)
