### ISSUE TITLE
Approfondimento e decodifica Blumlein

### ISSUE THREAD

**Issue by perlacat97** [s-e-a-m/SPhoMaMo#8]
va descritta meglio la problematica di ascolto di Blumlein su LR e aggiunta la soluzione di Gerzon

**Comment by perlacat97** [comment]
fatto :)

**Comment by grammaton** [comment]
Perla, hai scritto esattamente l'opposto di quello che abbiamo sperimentato.

**Comment by grammaton** [comment]
@perlacat97 ho fatto un `revert` del codice LaTeX per eliminare le cose che hai scritto. @perlacat97 @Petapton ho riportato i privilegi di scrittura a livello zero, così prima di pushare modifiche vanno revisionate via pull request
